In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.ensemble import VotingClassifier

In [23]:
df = pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [25]:
new_df  = pd.get_dummies(df, columns=['cp','sex','fbs', 'restecg','exang','slope','ca', 'thal'  ],dtype= float )

In [26]:
new_df.head()

,age,trestbps,chol,thalach,oldpeak,target,cp_0,cp_1,cp_2,cp_3,...,slope_2,ca_0,ca_1,ca_2,ca_3,ca_4,thal_0,thal_1,thal_2,thal_3
0,52,125,212,168,1.0,0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,53,140,203,155,3.1,0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,70,145,174,125,2.6,0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,61,148,203,161,0.0,0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,62,138,294,106,1.9,0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [40]:
x_new = new_df.drop('target', axis =1)
y_new = new_df['target']
x_new.shape,y_new.shape

((1025, 30), (1025,))

In [32]:
x_new.shape

(1025, 30)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [39]:
x = df.drop('target',axis =1)
y =df['target']
x.shape,y.shape

((1025, 13), (1025,))

In [38]:
from sklearn.model_selection import cross_val_score
import numpy as np 

best_k = []
for value in range(1,31):
    knn = KNeighborsClassifier(n_neighbors=value)
    score = cross_val_score(knn,x,y,cv = 10, scoring='accuracy')
    best_k.append(score.mean())

best_k_arr = np.array(best_k)
print(best_k_arr.argmax()+1, best_k_arr.max())
print(best_k)

1 0.9941747572815534
[np.float64(0.9941747572815534), np.float64(0.9629164287074052), np.float64(0.9433942509042452), np.float64(0.8349990481629546), np.float64(0.7599466971254522), np.float64(0.7629449838187702), np.float64(0.720911859889587), np.float64(0.7179421283076337), np.float64(0.7443080144679232), np.float64(0.7393965353131545), np.float64(0.7227869788692176), np.float64(0.7276413478012564), np.float64(0.7061964591661909), np.float64(0.7139920045688178), np.float64(0.7159242337711784), np.float64(0.7159337521416334), np.float64(0.7335237007424329), np.float64(0.7462402436702836), np.float64(0.7267371026080335), np.float64(0.7267656577193985), np.float64(0.7208261945554921), np.float64(0.7169046259280412), np.float64(0.7207881210736723), np.float64(0.7208261945554921), np.float64(0.7237483342851705), np.float64(0.725671045117076), np.float64(0.721787549971445), np.float64(0.710041880830002), np.float64(0.7139539310869979), np.float64(0.6954407005520655)]

In [ ]:
lor = LogisticRegression(max_iter=5000)
gnb = GaussianNB(var_smoothing=0.0001)
svc = SVC()

NameError: name 'train_test_split' is not defined

In [ ]:
from sklearn.feature_selection import mutual_info_classif

# A score of 0 or very close to 0. For mutual_info_classif
mi = mutual_info_classif(x,y,random_state=42)
mi_series = pd.Series(mi, index=x.columns).sort_values(ascending=False)
mi_series

chol        0.275314
thalach     0.147683
thal        0.136632
cp          0.135838
oldpeak     0.132645
ca          0.120577
exang       0.094500
trestbps    0.077058
age         0.051214
slope       0.050117
sex         0.033456
restecg     0.001491
fbs         0.000000
dtype: float64