In [8]:
import pandas as pd 
import numpy as np 
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [9]:
df = pd.read_csv('Titanic-Dataset.csv')
df.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [10]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [11]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [12]:
df = df[['Age', 'Fare','Survived','Pclass']]
df.head(4)

    Age     Fare  Survived  Pclass
0  22.0   7.2500         0       3
1  38.0  71.2833         1       1
2  26.0   7.9250         1       3
3  35.0  53.1000         1       1

In [13]:
x_train,x_test,y_train,y_test = train_test_split(df.drop('Survived',axis=1), df['Survived'],test_size=0.2, random_state=42)

In [15]:
knn = KNNImputer(n_neighbors= 2)
x_train_knn = knn.fit_transform(x_train)
x_test_knn = knn.transform(x_test)

In [19]:
x_train_knn.shape
x_train_knn[:5]

array([[45.5   , 28.5   ,  1.    ],
       [23.    , 13.    ,  2.    ],
       [32.    ,  7.925 ,  3.    ],
       [26.    ,  7.8542,  3.    ],
       [ 6.    , 31.275 ,  3.    ]])

In [20]:
lr = LogisticRegression()

lr.fit(x_train_knn, y_train)
y_pred = lr.predict(x_test_knn)
accuracy_score(y_test,y_pred)

0.7430167597765364

In [23]:
si = SimpleImputer(strategy='median')
x_train_si = si.fit_transform(x_train)
x_test_si = si.transform(x_test)
x_train_si[:5]

array([[45.5   , 28.5   ,  1.    ],
       [23.    , 13.    ,  2.    ],
       [32.    ,  7.925 ,  3.    ],
       [26.    ,  7.8542,  3.    ],
       [ 6.    , 31.275 ,  3.    ]])

In [24]:
lr.fit(x_train_si,y_train)
y_pred_si = lr.predict(x_test_si)
accuracy_score(y_test,y_pred_si)

0.7374301675977654

In [25]:
print(f'Knn accuracy :{accuracy_score(y_test,y_pred)}')
print(f'Simple IMputer accuracy :{accuracy_score(y_test,y_pred_si)}')

Knn accuracy :0.7430167597765364
Simple IMputer accuracy :0.7374301675977654

In [26]:
## now we will try to fill the missing values of the cabin column

cdf = pd.read_csv('Titanic-Dataset.csv')

cdf.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [ ]:
csi = SimpleImputer(strategy='most_frequent')
sidff = csi.fit_transform(cdf[['Cabin']])
sidff[:5]

array([['B96 B98'],
       ['C85'],
       ['B96 B98'],
       ['C123'],
       ['B96 B98']], dtype=object)