### Mixed Data

The data which is a mixture of numerical value as well as categorical value for example date, Indian raliways bougeys numbers.

Eg 12-march-2027, B34, C54

A data like this can be difficult to deal with in this notebook we will be dealin gwiht this kind of data 

Here is the link of the reference video :-  https://www.youtube.com/watch?v=9xiX-I5_LQY

In [1]:
import pandas as pd 
import numpy as np

In [3]:
df  = pd.read_csv('titanic.csv')
df.head()

  Cabin            Ticket number  Survived
0   NaN         A/5 21171      5         0
1   C85          PC 17599      3         1
2   NaN  STON/O2. 3101282      6         1
3  C123            113803      3         1
4   NaN            373450      A         0

In [4]:
df['number'].unique()

array(['5', '3', '6', 'A', '2', '1', '4'], dtype=object)

## In the above dataset we have two mix data columns that are ticket and number

In [5]:
## converting the number column to as follows  numeric value-> number_numeric  Categotical value -> number_categorical


df['number_numeric'] = pd.to_numeric(df['number'], errors = 'coerce', downcast = 'integer')

# what this peice of code will do is it convert the number col numeric value and add it to the the new column number numeric and for it is not bale to convert it would through an error but that would be ignored and replace witht NaN 

df.head()

  Cabin            Ticket number  Survived  number_numeric
0   NaN         A/5 21171      5         0             5.0
1   C85          PC 17599      3         1             3.0
2   NaN  STON/O2. 3101282      6         1             6.0
3  C123            113803      3         1             3.0
4   NaN            373450      A         0             NaN

In [ ]:
## Now for converting the categorical value in the number col to categorical value and add it to the  number_categorical col

df['number_categorical'] = np.where(df['number_numeric'].isnull(),df.number,np.nan)


# syntax of the np.where is as follows   
# np.where(condition, value_if_true, value_if_false)

# What the above code will do si check for the valeu in the number_numeric col if it is null and if it returns true it will add the original valeu from the number col and add it to the number categorical col and if the returns false it will return NaN

## Eg  
# Original (number)	number_numerical	number_categorical
# "123"	                123	                    NaN
# "45"	                 45	                    NaN
# "abc"	                NaN	                    "abc"
# "10xyz"	            NaN	                    "10xyz"

df.head()

  Cabin            Ticket number  Survived  number_numeric number_categorical
0   NaN         A/5 21171      5         0             5.0                NaN
1   C85          PC 17599      3         1             3.0                NaN
2   NaN  STON/O2. 3101282      6         1             6.0                NaN
3  C123            113803      3         1             3.0                NaN
4   NaN            373450      A         0             NaN                  A

In [7]:
# now we wil deal with the cabin col 


df.head()

  Cabin            Ticket number  Survived  number_numeric number_categorical
0   NaN         A/5 21171      5         0             5.0                NaN
1   C85          PC 17599      3         1             3.0                NaN
2   NaN  STON/O2. 3101282      6         1             6.0                NaN
3  C123            113803      3         1             3.0                NaN
4   NaN            373450      A         0             NaN                  A

In [8]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [15]:
## this hence we cannnot apply encoding on it as it would result in too many columnand it would be hard ofr us to interpret

df['cabin_number'] = df['Cabin'].str.extract(r'(\d+)')
# this will extract the number from the cabin col we have used regex pattern \d+ which will only extract numbers from the cabin col and add it to new col

df.head()

,Cabin,Ticket,number,Survived,number_numeric,number_categorical,cabin_number
0,NaN,A/5 21171,5,0,5.0,NaN,NaN
1,C85,PC 17599,3,1,3.0,NaN,85
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN
3,C123,113803,3,1,3.0,NaN,123
4,NaN,373450,A,0,NaN,A,NaN

In [16]:
df['cabin_cate'] = df['Cabin'].str[0]
# this will extract the first letter of the cabin col  As for our use case the Cabin col values has the letters are the first letter of the col followed by the number 

df.head()

,Cabin,Ticket,number,Survived,number_numeric,number_categorical,cabin_number,cabin_cate
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN
1,C85,PC 17599,3,1,3.0,NaN,85,C
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN
3,C123,113803,3,1,3.0,NaN,123,C
4,NaN,373450,A,0,NaN,A,NaN,NaN

In [20]:
## Now comes the final of handling the mixed variable which is the ticket col 

df['Ticket'].value_counts()

Ticket
347082              7
1601                7
CA. 2343            7
3101295             6
CA 2144             6
                   ..
PC 17590            1
17463               1
330877              1
373450              1
STON/O2. 3101282    1
Name: count, Length: 681, dtype: int64

In [28]:
df['ticket_number'] = df['Ticket'].apply(lambda x: x.split()[-1])
df['ticket_number'] = pd.to_numeric(df.ticket_number,errors = 'coerce',downcast = 'integer')

df.ticket_number.value_counts()

ticket_number
2343.0      7
347082.0    7
1601.0      7
2144.0      6
347088.0    6
           ..
392076.0    1
211536.0    1
112053.0    1
111369.0    1
330877.0    1
Name: count, Length: 678, dtype: int64

In [23]:
df['ticket_number_method2'] = df['Ticket'].str.extract(r'(\d+)')
df.ticket_number_method2.value_counts()

ticket_number_method2
5         21
2         20
4          8
1601       7
347082     7
          ..
392091     1
17592      1
347060     1
248706     1
350406     1
Name: count, Length: 635, dtype: int64

In [24]:
# we will be using the First methods as it is more accurate as the second method will only extract the number from the ticket col and it would not consider the case where there is no number in the ticket col and it would return NaN for those cases which is not what we want as we want to keep the original value for those cases where there is no number in the ticket col
df.drop(['ticket_number_method2'],axis =1 , inplace = True)

In [30]:
df["ticket_categorical"] = df['Ticket'].apply(lambda x: x.split()[0])
df.ticket_categorical = np.where(df.ticket_categorical.str.isnumeric(),np.nan,df.ticket_categorical)

df.head()

,Cabin,Ticket,number,Survived,number_numeric,number_categorical,cabin_number,cabin_cate,ticket_number,ticket_categorical
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN,21171.0,A/5
1,C85,PC 17599,3,1,3.0,NaN,85,C,17599.0,PC
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN,3101282.0,STON/O2.
3,C123,113803,3,1,3.0,NaN,123,C,113803.0,NaN
4,NaN,373450,A,0,NaN,A,NaN,NaN,373450.0,NaN